"""empty message

Revision ID: f89d3ee95725
Revises: 819cbf6e030b
Create Date: 2023-10-15 17:54:22.646651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f89d3ee95725"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
